apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-wiki
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: go-wiki
    spec:
      containers:
      - image: <image path>
        name: go-wiki
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: go-wiki
  name: go-wiki
spec:
  ports:
  - port: 8080
  selector:
    name: go-wiki
  type: LoadBalancer
